services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./api/.env
    restart: always

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    depends_on:
      - api
      - socket

  socket:
    build:
      context: ./socket
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./socket/.env
    restart: always
